services:
  - postgresql
before_script:
  - psql -c 'create database addict_test;' -U postgres
language: elixir
elixir:
  - 1.4.2
otp_release:
  - 18.2.1
sudo: false
notifications:
  recipients:
    - nizar.venturini@gmail.com
